# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='voted',
            field=models.ManyToManyField(related_name='voted', to='ask.Profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='ask.Profile'),
        ),
        migrations.AddField(
            model_name='tag',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
