# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20170515_0921'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
